export const components = {
  common: ['/components/Icon', '/components/Color', '/components/Button'],
  layout: ['/components/Space'],
  // navigation: [
  //   '/components/capsule-tabs',
  //   '/components/index-bar',
  //   '/components/jumbo-tabs',
  //   '/components/nav-bar',
  //   '/components/side-bar',
  //   '/components/tab-bar',
  //   '/components/tabs',
  // ],
  dataDisplay: ['/components/Badge'],
  // dataEntry: [
  //   '/components/cascader',
  //   '/components/cascader-view',
  //   '/components/check-list',
  //   '/components/checkbox',
  //   '/components/form',
  //   '/components/input',
  //   '/components/picker',
  //   '/components/picker-view',
  //   '/components/radio',
  //   '/components/rate',
  //   '/components/search-bar',
  //   '/components/selector',
  //   '/components/slider',
  //   '/components/stepper',
  //   '/components/switch',
  //   '/components/text-area',
  // ],
  feedback: ['/components/Loading', '/components/Alert'],
  // guidance: ['/components/badge', '/components/notice-bar'],
  // other: ['/components/LocaleProvider'],
};
